//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingCartCookie {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label userlabel;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.CheckBoxList items;
		
		protected System.Web.UI.WebControls.Button continueShopping;
		
		protected System.Web.UI.WebControls.Button ViewList;
		
		protected System.Web.UI.WebControls.Label itemsList;
		
		protected System.Web.UI.WebControls.Button refresh;
	}
}
