//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessionStateLab5_2 {
	
	
	public partial class SecondPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label name;
		
		protected System.Web.UI.WebControls.Label roll;
		
		protected System.Web.UI.WebControls.Label subj;
		
		protected System.Web.UI.WebControls.Button counter;
		
		protected System.Web.UI.WebControls.Label count;
	}
}
