//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList ddl1;
		
		protected System.Web.UI.WebControls.Label labelAns;
		
		protected System.Web.UI.WebControls.Image image1;
		
		protected System.Web.UI.WebControls.Label name;
		
		protected System.Web.UI.WebControls.TextBox ename;
		
		protected System.Web.UI.WebControls.Label dojLabel;
		
		protected System.Web.UI.WebControls.TextBox doj;
		
		protected System.Web.UI.WebControls.Label y_n;
	}
}
