//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazineCover {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.RadioButtonList lstimage;
		
		protected System.Web.UI.WebControls.TextBox title;
		
		protected System.Web.UI.WebControls.TextBox inputText;
		
		protected System.Web.UI.WebControls.Button generate;
		
		protected System.Web.UI.WebControls.Panel pnlCover;
		
		protected System.Web.UI.WebControls.Label lblTitle;
		
		protected System.Web.UI.WebControls.Label lblInput;
	}
}
