//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carManufacturer_QueryString {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList carManufacturerList;
		
		protected System.Web.UI.WebControls.TextBox model_name;
		
		protected System.Web.UI.WebControls.Button Display;
		
		protected System.Web.UI.WebControls.Label invalid;
	}
}
