//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentForm_Lab6Q1 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl studentForm;
		
		protected System.Web.UI.WebControls.DropDownList candList;
		
		protected System.Web.UI.WebControls.RadioButtonList houseList;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqlist;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqHouse;
		
		protected System.Web.UI.WebControls.TextBox @class;
		
		protected System.Web.UI.WebControls.RangeValidator classValid;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator emailValid;
		
		protected System.Web.UI.WebControls.TextBox contact;
		
		protected System.Web.UI.WebControls.CustomValidator contactValid;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.WebControls.Label success;
		
		protected System.Web.UI.WebControls.ValidationSummary valid;
	}
}
