//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPage {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox emailID;
		
		protected System.Web.UI.WebControls.TextBox pswd;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.WebControls.Label failed;
	}
}
